# frozen_string_literal: true

module Agents
  # Agent #5: when a sprint is under client review, synthesize executive review and
  # auto-log change/enhancement items as completed agenda items.
  class SprintExecutiveReview
    class Error < StandardError; end

    class << self
      def call(sprint:)
        raise Error, "Mark the sprint as under client review first." unless sprint.under_client_review?

        project = sprint.project
        items = sprint.agenda_items.order(:status, :title)

        lines = []
        lines << "## Sprint: #{sprint.name}"
        lines << "Goal: #{sprint.goal}"
        lines << "Items (#{items.size}):"
        items.each do |i|
          lines << "- [#{i.status}] #{i.title} — figma: #{i.figma_screen_url.present? ? 'linked' : 'none'}"
        end

        raw = Agents::OpenAiChat.json_content!(
          messages: [
            {
              role: "system",
              content: <<~SYS.strip
                You are a principal engineer + delivery lead.
                Output strict JSON with keys:
                {
                  "executive_review_markdown": "markdown text",
                  "change_items": [{"title":"...", "details":"...", "type":"missing|changed|enhancement"}]
                }
                Requirements:
                - Sprint health vs original intent (use wireframe outline + dev spec when present).
                - Clearly list missing/changed/enhancement items in change_items.
                - What is solid vs still open.
                Keep executive_review_markdown under 900 words.
              SYS
            },
            {
              role: "user",
              content: <<~USR.strip
                Wireframe outline (may be empty):
                #{project.wireframe_outline.to_s.truncate(8000)}

                Development task spec (may be empty):
                #{project.dev_task_spec_markdown.to_s.truncate(8000)}

                Agenda snapshot:
                #{lines.join("\n").truncate(12_000)}
              USR
            }
          ],
          max_tokens: 3500
        )

        raise Error, "Empty review from model" if raw.blank?
        payload = parse_payload!(raw)
        create_change_items!(sprint:, payload:)

        sprint.update!(ai_executive_review: payload[:executive_review_markdown])
        { ok: true, changes_added: payload[:change_items].size }
      end

      private

      def parse_payload!(raw)
        data = JSON.parse(raw)
        markdown = data["executive_review_markdown"].to_s.strip
        raise Error, "Model JSON missing executive_review_markdown" if markdown.blank?

        changes = Array(data["change_items"]).filter_map do |h|
          next unless h.is_a?(Hash)

          title = h["title"].to_s.strip
          details = h["details"].to_s.strip
          type = h["type"].to_s.strip.presence || "changed"
          next if title.blank?

          { title: title.truncate(220), details: details, type: type }
        end

        { executive_review_markdown: markdown, change_items: changes }
      rescue JSON::ParserError
        raise Error, "Model returned invalid JSON."
      end

      def create_change_items!(sprint:, payload:)
        payload[:change_items].each do |row|
          title = "[Review][#{row[:type]}] #{row[:title]}"
          existing = sprint.agenda_items.where("title ILIKE ?", title).exists?
          next if existing

          AgendaItem.create!(
            client_id: sprint.project.client_id,
            project_id: sprint.project_id,
            sprint_id: sprint.id,
            title: title,
            description: [
              "Generated by dev review agent (#5).",
              row[:details].presence
            ].compact.join("\n\n"),
            agent_source: "sprint_review_agent",
            checklist: [],
            work_stream: :enhancement,
            status: :completed,
            priority_level: :normal,
            complexity: 2,
            due_on: Date.current,
            completed_at: Time.current
          )
        end
      end
    end
  end
end
